version: "3"

services:
  backend:
    build: "./backend"
    volumes:
      - ./backend:/home/node/app
    ports:
      - 3000:3000
  frontend:
    build: "./frontend"
    volumes:
      - ./frontend:/home/node/app
    ports:
      - 7777:7777
    depends_on:
      - backend